package com.kenny.mybatis.api;

import org.mybatis.generator.api.CommentGenerator;
import org.mybatis.generator.api.dom.xml.TextElement;
import org.mybatis.generator.api.dom.xml.XmlElement;
import org.mybatis.generator.config.MergeConstants;
import org.mybatis.generator.internal.DefaultCommentGenerator;

public class CustomComment extends DefaultCommentGenerator implements CommentGenerator {


    @Override
    public void addComment(XmlElement xmlElement) {

        xmlElement.addElement(new TextElement("<!--")); //$NON-NLS-1$

        StringBuilder sb = new StringBuilder();
        sb.append("  WARNING - "); //$NON-NLS-1$
        sb.append(MergeConstants.NEW_ELEMENT_TAG);
        xmlElement.addElement(new TextElement(sb.toString()));
        xmlElement.addElement(new TextElement(
                        "  This element is automatically generated by MyBatis Generator, do not modify.")); //$NON-NLS-1$

        sb.setLength(0);
        sb.append("  This element was generated on "); //$NON-NLS-1$
        sb.append('.');
        xmlElement.addElement(new TextElement(sb.toString()));

        xmlElement.addElement(new TextElement("-->")); //$NON-NLS-1$
    }
}
